testname: MUSHRA_remix
testId: MUSHRA_remix
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Welcome
      content: |
        <!DOCTYPE html>
        <html>
        <head>
          <title>Music Grading Test Instructions</title>
        </head>
        <body>

        <h2><strong>Test Instructions</strong></h2>

        <p>Hello and welcome to this music grading test! We're excited to have you here. In this test, we're going to listen to some remixed versions of a song and assign grades to them using a scale. Don't worry, it's going to be a <strong>fun and enjoyable</strong> experience!</p>
        
        <img src="../configs/resources/images/DJman.png" width="300" height="300">
        
        <h3><strong>Purpose of the Test:</strong></h3>
        <p>The purpose of this test is to help us understand your preferences for different remixed versions of a song. Your grades will help us figure out which versions you find the <strong>most enjoyable</strong>.</p>
        
        <h3><strong>How the Test Works:</strong></h3>
        <ul>
          <li>In each trial, you will listen to <strong>7 different remixed versions</strong> of a song.</li>
          <li>Your job is to listen to each version and decide which one you find the <strong>most enjoyable</strong>. This version will be your <strong>reference</strong>, and you'll assign it a grade of <strong>100</strong>.</li>
          <li>After you've selected the most enjoyable version, you will compare the other versions to this reference. Assign scores from <strong>0 to 100</strong> based on how much you like each version compared to your reference.</li>
        </ul>
        
        <h3><strong>Listening and Grading:</strong></h3>
        <ul>
          <li>You are free to listen to the versions <strong>in any order you like</strong>.</li>
          <li>You can listen to each version as <strong>many times</strong> as you want before assigning a grade.</li>
          <li>Remember, you're the expert here! Your grades will help us understand your <strong>musical preferences</strong>.</li>
        </ul>
        
        <h3><strong>Grading Scale:</strong></h3>
        <ul>
          <li><strong>100</strong>: The version you find most enjoyable. You'll assign this score to your reference version.</li>
          <li><strong>0-100</strong>: For other versions, assign a score based on how much you like them compared to your reference.</li>
        </ul>
        
        <h3><strong>Important Notes:</strong></h3>
        <ul>
          <li>There are <strong>no right or wrong answers</strong>. We're interested in your <strong>personal preferences</strong>.</li>
          <li>Take your time, enjoy the music, and have <strong>fun</strong> with this test!</li>
        </ul>
        
        <p>Thank you for participating, and let's get started! If you have any questions, feel free to ask the test conductor.</p>

        </body>
        </html>
    - type: consent
      id: consent_page
      name: Consent
      mustConsent: true
      content: <p>You are participating in a listening test. For this, we want to store the answers you give to the following questions.<br>Do you give consent for this?</p>
    - type: volume
      id: volume
      name: Volume Calibration
      content: |
          <p>Welcome to the Volume Calibration page.</p>
          <p>In this part of the test, we want to make sure that the volume of the sounds is just right for you. You'll be listening to a short sound clip, and we'd like you to adjust the volume to the most comfortable level for your ears.</p>
          <p>When you're ready, click the "Play" button to listen to the sound. Then, use the slider to increase or decrease the volume until it's comfortable for you. Don't worry, there's no right or wrong answer!</p>
          <p>Once you've set the volume to your liking, you can move on to the next part of the test. Have fun!</p>
      stimulus: configs/resources/audio/mono_c1.wav
      defaultVolume: 0.7
    - type: likert_multi_stimulus
      id: lms4
      name: likert
      mustRate: true
      randomize: true
      content: |
        <p><strong>Familiarity Rating for Songs</strong></p>
        <p><strong>Hello!</strong> We have a fun activity for you where you can let us know how well you know different songs.</p>
        <p><strong>Here's what you need to do:</strong></p>
        <ol>
          <li><strong>Step 1:</strong> You'll see a list of songs. We want to know how familiar you are with each song. Familiar means how well you know or recognize the song.</li>
          <li><strong>Step 2:</strong> Look at the scale below each song. The scale has levels that show how well you know the song. Choose the level that best describes your familiarity with the song:</li>
        </ol>
        <blockquote>
          <ul>
            <li>Very Familiar</li>
            <li>Quite Familiar</li>
            <li>Somewhat Familiar</li>
            <li>Not Very Familiar</li>
            <li>Not Familiar at All</li>
          </ul>
        </blockquote>
        <p><strong>Remember:</strong> It's okay to not know some songs, and it's great if you know others really well! Just have fun and be honest with your choices.</p>
        <p>Enjoy rating the songs and telling us how well you know them! Your opinion is important, so thank you for sharing it with us! ðŸŽµðŸŽ¶</p>      
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav
      response:
        - value: Not Familiar at All
          label: Not Familiar at All
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Not Very Familiar
          label: Not Very Familiar
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Somewhat Familiar
          label: Somewhat Familiar
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Not Very Familiar
          label: Not Very Familiar
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Not Familiar at All
          label: Not Familiar at All
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png          
          
    - type: mushra
      id: trial1
      name: MUSHRA
      content: This training shows how to use our user interface. Please perform the underlined instructions to proceed with the training session. Reminder: In a MUSHRA listening test you are asked to rate the Basic Audio Quality (BAQ) of each condition.<br/>Basic Audio Quality is a single and global attribute that is used to judge any and all detected differences between the reference and the condition.
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/mono_ref.wav
      createAnchor35: true
      createAnchor70: true
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav
    - 
          - random
          - type: mushra
            id: trial_random_1
            name: MUSHRA TEST - ORIGINAL -
            content: Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true
            showWaveform: true
            reference: configs/Niyazi/Normal/1/standard.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/Niyazi/Normal/1/-3dB.wav
                C2: configs/Niyazi/Normal/1/-6dB.wav
                C3: configs/Niyazi/Normal/1/-9dB.wav
                C4: configs/Niyazi/Normal/1/-12dB.wav
                C5: configs/Niyazi/Normal/1/vdb.wav
                C6: configs/Niyazi/Normal/1/anchor.wav
          - type: mushra
            id: trial_random_2
            name: MUSHRA TEST - ORIGINAL -
            content: Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true
            showWaveform: true
            reference: configs/Niyazi/Normal/2/standard.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/Niyazi/Normal/2/-3dB.wav
                C2: configs/Niyazi/Normal/2/-6dB.wav
                C3: configs/Niyazi/Normal/2/-9dB.wav
                C4: configs/Niyazi/Normal/2/-12dB.wav
                C5: configs/Niyazi/Normal/2/vdb.wav
                C6: configs/Niyazi/Normal/2/anchor.wav
          - type: mushra
            id: trial_random_3
            name: MUSHRA TEST - ORIGINAL -
            content: Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true
            showWaveform: true
            reference: configs/Niyazi/Normal/3/standard.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/Niyazi/Normal/3/-3dB.wav
                C2: configs/Niyazi/Normal/3/-6dB.wav
                C3: configs/Niyazi/Normal/3/-9dB.wav
                C4: configs/Niyazi/Normal/3/-12dB.wav
                C5: configs/Niyazi/Normal/3/vdb.wav
                C6: configs/Niyazi/Normal/3/anchor.wav
          - type: mushra
            id: trial_random_4
            name: MUSHRA TEST - ORIGINAL -
            content: Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true
            showWaveform: true
            reference: configs/Niyazi/Normal/4/standard.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/Niyazi/Normal/4/-3dB.wav
                C2: configs/Niyazi/Normal/4/-6dB.wav
                C3: configs/Niyazi/Normal/4/-9dB.wav
                C4: configs/Niyazi/Normal/4/-12dB.wav
                C5: configs/Niyazi/Normal/4/vdb.wav
                C6: configs/Niyazi/Normal/4/anchor.wav
          - type: mushra
            id: trial_random_5
            name: MUSHRA TEST - ORIGINAL -
            content: Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true
            showWaveform: true
            reference: configs/Niyazi/Normal/5/standard.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/Niyazi/Normal/5/-3dB.wav
                C2: configs/Niyazi/Normal/5/-6dB.wav
                C3: configs/Niyazi/Normal/5/-9dB.wav
                C4: configs/Niyazi/Normal/5/-12dB.wav
                C5: configs/Niyazi/Normal/5/vdb.wav
                C6: configs/Niyazi/Normal/5/anchor.wav
          - type: mushra
            id: trial_random_6
            name: MUSHRA TEST - ORIGINAL -
            content: Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true
            showWaveform: true
            reference: configs/Niyazi/Normal/6/standard.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/Niyazi/Normal/6/-3dB.wav
                C2: configs/Niyazi/Normal/6/-6dB.wav
                C3: configs/Niyazi/Normal/6/-9dB.wav
                C4: configs/Niyazi/Normal/6/-12dB.wav
                C5: configs/Niyazi/Normal/6/vdb.wav
                C6: configs/Niyazi/Normal/6/anchor.wav
          - type: mushra
            id: trial_random_7
            name: MUSHRA TEST - ORIGINAL -
            content: Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true
            showWaveform: true
            reference: configs/Niyazi/Normal/7/standard.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/Niyazi/Normal/7/-3dB.wav
                C2: configs/Niyazi/Normal/7/-6dB.wav
                C3: configs/Niyazi/Normal/7/-9dB.wav
                C4: configs/Niyazi/Normal/7/-12dB.wav
                C5: configs/Niyazi/Normal/7/vdb.wav
                C6: configs/Niyazi/Normal/7/anchor.wav
          - type: mushra
            id: trial_random_8
            name: MUSHRA TEST - ORIGINAL -
            content: Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true
            showWaveform: true
            reference: configs/Niyazi/Normal/8/standard.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/Niyazi/Normal/8/-3dB.wav
                C2: configs/Niyazi/Normal/8/-6dB.wav
                C3: configs/Niyazi/Normal/8/-9dB.wav
                C4: configs/Niyazi/Normal/8/-12dB.wav
                C5: configs/Niyazi/Normal/8/vdb.wav
                C6: configs/Niyazi/Normal/8/anchor.wav
          - type: mushra
            id: trial_random_9
            name: MUSHRA TEST - ORIGINAL -
            content: Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true
            showWaveform: true
            reference: configs/Niyazi/Normal/9/standard.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/Niyazi/Normal/9/-3dB.wav
                C2: configs/Niyazi/Normal/9/-6dB.wav
                C3: configs/Niyazi/Normal/9/-9dB.wav
                C4: configs/Niyazi/Normal/9/-12dB.wav
                C5: configs/Niyazi/Normal/9/vdb.wav
                C6: configs/Niyazi/Normal/9/anchor.wav
          - type: mushra
            id: trial_random_10
            name: MUSHRA TEST - ORIGINAL -
            content: Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true
            showWaveform: true
            reference: configs/Niyazi/Normal/10/standard.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/Niyazi/Normal/10/-3dB.wav
                C2: configs/Niyazi/Normal/10/-6dB.wav
                C3: configs/Niyazi/Normal/10/-9dB.wav
                C4: configs/Niyazi/Normal/10/-12dB.wav
                C5: configs/Niyazi/Normal/10/vdb.wav
                C6: configs/Niyazi/Normal/10/anchor.wav
    - type: finish
      name: Thank you
      content: Thank you for attending!
      showResults: true
      writeResults: true
      questionnaire:
          - type: text
            label: eMail
            name: email
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          - type: likert
            name: gender
            label: Gender
            response:
             - value: female
               label: Female
             - value: male
               label: Male
             - value: other
               label: Other
